name: note_app

description: "A simple and efficient note-taking Flutter app."

publish_to: "none"

version: 1.1.0+2

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    outline_material_icons: ^1.0.0
    sqflite: ^2.4.1
    path: ^1.9.0
    shared_preferences: ^2.2.2
    intl: ^0.19.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
